# Login shell configuration

export PATH="$HOME/.local/bin:$PATH";
#export PATH="/opt/homebrew/opt/curl/bin:$PATH";
export PATH="/opt/homebrew/opt/node@18/bin:$PATH"

# Added by Toolbox App
export PATH="$PATH:/Users/russ/Library/Application Support/JetBrains/Toolbox/scripts"

eval "$(/opt/homebrew/bin/brew shellenv)"
